Can disable deselection on click
weweb-assets/ww-input-select pull request #44
Opened 2022-07-28 10:43 UTC by AurelieV

2022-07-28 10:44 UTC, AlexisJC approved these changes

2022-07-28 10:45 UTC, kevinbarfleur approved these changes

2022-07-29 09:03 UTC, Dams-d requested changes

2022-07-29 09:03 UTC, Dams-d commented on ww-config.js
> +                en: 'Can deselect',
Can we use unselect instead of deselect?

2022-08-01 12:50 UTC, Dams-d approved these changes

2022-08-01 12:51 UTC, merged