Ww 1409 virtual scroll
weweb-assets/ww-input-select pull request #70
Opened 2023-01-31 09:32 UTC by kevinbarfleur

2023-02-10 09:52 UTC, AurelieV requested changes
Same comment than the multiselect

2023-02-20 22:41 UTC, kevinbarfleur commented
On date

2023-03-07 13:35 UTC, AurelieV approved these changes

2023-03-08 09:15 UTC, MarcFabre approved these changes

2023-04-05 07:15 UTC, merged